name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore source/vbeDecoder.sln
    - name: Building Libraries
      run: dotnet build source/libraries/vbeDecoder.NetStandard/vbeDecoder.csproj --no-restore
    - name: Building netStandard CLI
      run: dotnet build source/cli-projects/vbeDecoder.CLI.NetStandard2/vbeDecoder.CLI.csproj --no-restore
    - name: Building netCore CLI
      run: dotnet build source/cli-projects/vbeDecoder.CLI.NetCore/vbeDecoder.CLI.Core.csproj --no-restore
    - name: Test
      run: dotnet test source/cli-projects/vbeDecoder.CLI.NetCore/vbeDecoder.CLI.Core.csproj --no-build --verbosity normal
